name = "nodewarden"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = false

[build]
command = "npm run build"

[triggers]
crons = [ "*/5 * * * *" ]

[[durable_objects.bindings]]
name = "NOTIFICATIONS_HUB"
class_name = "NotificationsHub"

[[kv_namespaces]]
binding = "ATTACHMENTS_KV"
id = "f57a747eb4934d36951ddec37eff5f1a"
binding = "KV_BINDING"
id = "a0ba4881359948e99bee553f789125cf" 

[[migrations]]
tag = "v1-notifications-hub"
new_sqlite_classes = [ "NotificationsHub" ]
